In [4]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import explained_variance_score, max_error, r2_score
import plotly.express as px
import seaborn as sns

In [5]:
df = px.data.iris()

,sepal_length,sepal_width,petal_length,petal_width,species,species_id
0,5.1,3.5,1.4,0.2,setosa,1
1,4.9,3.0,1.4,0.2,setosa,1
2,4.7,3.2,1.3,0.2,setosa,1
3,4.6,3.1,1.5,0.2,setosa,1
4,5.0,3.6,1.4,0.2,setosa,1
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,3
146,6.3,2.5,5.0,1.9,virginica,3
147,6.5,3.0,5.2,2.0,virginica,3
148,6.2,3.4,5.4,2.3,virginica,3
149,5.9,3.0,5.1,1.8,virginica,3

In [7]:
X = df.iloc[:,2].values # petal_length
Y = df.iloc[:,3].values #petal_width

In [8]:
X = X.reshape(-1, 1)
Y = Y.reshape(-1, 1)

In [9]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, random_state=0)

In [10]:
model = LinearRegression().fit(x_train, y_train)

In [15]:
predictions = model.predict(x_test)

print("coef: "+ str(model.coef_))
print("intercept: " +str(model.intercept_))
print("train R squared: " + str(model.score(x_train, y_train)))
print("test R squared: " + str(model.score(x_test,y_test)))
print("max error: " + str(max_error(y_test, predictions)))


print("explained variance score:" + str(explained_variance_score(y_test, predictions)))
print("r2 score:" + str(r2_score(y_test, predictions)))

coef: [[0.42045324]]
intercept: [-0.37389925]
train R squared: 0.9357671871718698
test R squared: 0.8925105635886209
max error: 0.6295877440532185
explained variance score:0.894442659930156
r2 score:0.8925105635886209

In [16]:
X = df.iloc[:,0].values # sepal_length
Y = df.iloc[:,3].values #petal_width

X = X.reshape(-1, 1)
Y = Y.reshape(-1, 1)

x_train, x_test, y_train, y_test = train_test_split(X, Y, random_state=0)

model = LinearRegression().fit(x_train, y_train)

predictions = model.predict(x_test)

print("coef: "+ str(model.coef_))
print("intercept: " +str(model.intercept_))
print("train R squared: " + str(model.score(x_train, y_train)))
print("test R squared: " + str(model.score(x_test,y_test)))
print("max error: " + str(max_error(y_test, predictions)))


print("explained variance score:" + str(explained_variance_score(y_test, predictions)))
print("r2 score:" + str(r2_score(y_test, predictions)))

predictions = model.predict(x_test)

print("coef: "+ str(model.coef_))
print("intercept: " +str(model.intercept_))
print("train R squared: " + str(model.score(x_train, y_train)))
print("test R squared: " + str(model.score(x_test,y_test)))
print("max error: " + str(max_error(y_test, predictions)))


print("explained variance score:" + str(explained_variance_score(y_test, predictions)))
print("r2 score:" + str(r2_score(y_test, predictions)))

coef: [[0.75345377]]
intercept: [-3.21296493]
train R squared: 0.7035806902311454
test R squared: 0.5373244898561502
max error: 1.2429330499468656
explained variance score:0.5398829789613668
r2 score:0.5373244898561502
coef: [[0.75345377]]
intercept: [-3.21296493]
train R squared: 0.7035806902311454
test R squared: 0.5373244898561502
max error: 1.2429330499468656
explained variance score:0.5398829789613668
r2 score:0.5373244898561502